services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:${PB_VERSION}
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv # optional
      - ENCRYPTION # optional
    # environment:
      # ENCRYPTION: $(openssl rand -hex 16) # optional (Ensure this is a 32-character long encryption key https://pocketbase.io/docs/going-to-production/#enable-settings-encryption) 
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations # optional
      - ./pocketbase/pb_public:/pb_public # optional
      - ./pocketbase/pb_hooks:/pb_hooks # optional
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}